version: '3.7'

services:
  devcontainer:
    image: ${image_name}:0.1
    build: .
    container_name: ${container_name}
    hostname: ${hostname_local}.local
    working_dir: /src
    volumes:
       - ..:/src
       # Allow AWS CLI and other tools to read an AWS profile
       - ~/.aws:/home/node/.aws
    command: sleep infinity